<a href="https://colab.research.google.com/github/Mahesh3146/deep_learning_using_tensorflow/blob/main/fundamental_of_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf


In [3]:
scalar = tf.constant(10)

In [4]:
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [5]:
vector = tf.constant([2,3,4,5,6,7,8,9,10])
vector

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [6]:
matrix = tf.constant([[23,45,60,87,29],[56,78,29,10,30],[30,8290,102834,556,2390]])
matrix

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[    23,     45,     60,     87,     29],
       [    56,     78,     29,     10,     30],
       [    30,   8290, 102834,    556,   2390]], dtype=int32)>

In [7]:
scalar.ndim

0

In [8]:
vector.ndim

1

In [9]:
matrix.ndim

2

In [11]:
tensors = tf.constant([[[23,4,5,67],[45,67,85,23]],[[34,56,2,3],[12,30,18,23]],[[86,38,30,21],[45,98,20,30]]])

tensors

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[23,  4,  5, 67],
        [45, 67, 85, 23]],

       [[34, 56,  2,  3],
        [12, 30, 18, 23]],

       [[86, 38, 30, 21],
        [45, 98, 20, 30]]], dtype=int32)>

In [12]:
tensors.ndim

3

In [13]:
scalar1 = tf.constant(387620291)
scalar1
scalar.ndim

0

In [14]:
scalar1

<tf.Tensor: shape=(), dtype=int32, numpy=387620291>

In [15]:
vectors1 = tf.constant([456,2948,582,105869,38462,450298])
vectors1

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([   456,   2948,    582, 105869,  38462, 450298], dtype=int32)>

In [16]:
vectors1.ndim

1

In [17]:
matrix1 = tf.constant([[3745,282,182],[2874,2023,182]])

In [18]:
matrix1



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3745,  282,  182],
       [2874, 2023,  182]], dtype=int32)>

In [19]:
matrix1.ndim

2

In [21]:
tensor1 = tf.constant([[[23,45,67],[273,586,89]],[[645,274,3895],[5758,2038,2839]],[[758,29484,2934],[845,8346,3945]]])
tensor1


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[   23,    45,    67],
        [  273,   586,    89]],

       [[  645,   274,  3895],
        [ 5758,  2038,  2839]],

       [[  758, 29484,  2934],
        [  845,  8346,  3945]]], dtype=int32)>

In [22]:
tensor1.ndim

3