<a href="https://colab.research.google.com/github/Mahesh3146/deep_learning_using_tensorflow/blob/main/fundamental_of_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import tensorflow as tf


In [ ]:
scalar = tf.constant(10)

In [ ]:
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
vector = tf.constant([2,3,4,5,6,7,8,9,10])
vector

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [ ]:
matrix = tf.constant([[23,45,60,87,29],[56,78,29,10,30],[30,8290,102834,556,2390]])
matrix

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[    23,     45,     60,     87,     29],
       [    56,     78,     29,     10,     30],
       [    30,   8290, 102834,    556,   2390]], dtype=int32)>

In [ ]:
scalar.ndim

0

In [ ]:
vector.ndim

1

In [ ]:
matrix.ndim

2

In [ ]:
tensors = tf.constant([[[23,4,5,67],[45,67,85,23]],[[34,56,2,3],[12,30,18,23]],[[86,38,30,21],[45,98,20,30]]])

tensors

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[23,  4,  5, 67],
        [45, 67, 85, 23]],

       [[34, 56,  2,  3],
        [12, 30, 18, 23]],

       [[86, 38, 30, 21],
        [45, 98, 20, 30]]], dtype=int32)>

In [ ]:
tensors.ndim

3

In [ ]:
scalar1 = tf.constant(387620291)
scalar1
scalar.ndim

0

In [ ]:
scalar1

<tf.Tensor: shape=(), dtype=int32, numpy=387620291>

In [ ]:
vectors1 = tf.constant([456,2948,582,105869,38462,450298])
vectors1

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([   456,   2948,    582, 105869,  38462, 450298], dtype=int32)>

In [ ]:
vectors1.ndim

1

In [ ]:
matrix1 = tf.constant([[3745,282,182],[2874,2023,182]])

In [ ]:
matrix1



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3745,  282,  182],
       [2874, 2023,  182]], dtype=int32)>

In [ ]:
matrix1.ndim

2

In [ ]:
tensor1 = tf.constant([[[23,45,67],[273,586,89]],[[645,274,3895],[5758,2038,2839]],[[758,29484,2934],[845,8346,3945]]])
tensor1


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[   23,    45,    67],
        [  273,   586,    89]],

       [[  645,   274,  3895],
        [ 5758,  2038,  2839]],

       [[  758, 29484,  2934],
        [  845,  8346,  3945]]], dtype=int32)>

In [ ]:
tensor1.ndim

3

# creating variable tensors

In [1]:
import tensorflow as tf

In [3]:
changeble_tensor = tf.Variable([45,67])
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([45, 67], dtype=int32)>

In [4]:
changeble_tensor[0] = 1

TypeError: ignored

In [5]:
changeble_tensor[0].assign(3)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 3, 67], dtype=int32)>

In [6]:
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 3, 67], dtype=int32)>

In [9]:
changeble_tensor2 = tf.Variable([67,89,20,37])
changeble_tensor2


<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([67, 89, 20, 37], dtype=int32)>

In [10]:
unchangeble_tensor3 = tf.constant([56,29,283,49])
unchangeble_tensor3

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 56,  29, 283,  49], dtype=int32)>

In [11]:
changeble_tensor2[2].assign(79)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([67, 89, 79, 37], dtype=int32)>

In [12]:
unchangeble_tensor3[1].assign(54)

AttributeError: ignored

In [15]:

import tensorflow as tf
random_tensor = tf.random.Generator.from_seed(56)
random_tensor = random_tensor.normal(shape=(4,3))


In [16]:
random_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.67958915,  0.44723678, -0.17811584],
       [ 0.24882518,  0.49689844,  0.8259971 ],
       [ 1.0340209 , -0.24918637, -1.5780283 ],
       [-0.92161775,  0.268676  ,  0.9418312 ]], dtype=float32)>

In [17]:
import tensorflow as tf
random_tensor1 = tf.random.Generator.from_seed(34)
random_tensor1 = random_tensor1.normal(shape = (5,6))
random_tensor1

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174,  0.495291  ,
        -0.648484  ],
       [-1.8700892 ,  2.7830641 , -0.645002  ,  0.18022095, -0.14656258,
         0.34374258],
       [ 0.41367555,  0.17573498, -1.0871261 ,  0.45905176,  0.20386009,
         0.562024  ],
       [-2.3001142 , -1.349454  ,  0.81485   ,  1.2790666 ,  0.02203509,
         1.5428121 ],
       [ 0.78953624,  0.53897345, -0.48535708,  0.74055266,  0.31662667,
        -1.4391748 ]], dtype=float32)>

In [18]:
import tensorflow as tf
random_tensor3 = tf.random.Generator.from_seed(34)
random_tensor3 = random_tensor3.normal(shape=(5,6))
random_tensor3

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174,  0.495291  ,
        -0.648484  ],
       [-1.8700892 ,  2.7830641 , -0.645002  ,  0.18022095, -0.14656258,
         0.34374258],
       [ 0.41367555,  0.17573498, -1.0871261 ,  0.45905176,  0.20386009,
         0.562024  ],
       [-2.3001142 , -1.349454  ,  0.81485   ,  1.2790666 ,  0.02203509,
         1.5428121 ],
       [ 0.78953624,  0.53897345, -0.48535708,  0.74055266,  0.31662667,
        -1.4391748 ]], dtype=float32)>

In [19]:
random_tensor4 = tf.random.Generator.from_seed(78)
random_tensor4 = random_tensor4.uniform(shape=(3,5))
random_tensor4

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.06560767, 0.6030959 , 0.5261806 , 0.29263592, 0.36828172],
       [0.9125351 , 0.9311757 , 0.80997777, 0.88897777, 0.38208318],
       [0.46514285, 0.26686597, 0.57392883, 0.9305825 , 0.97072124]],
      dtype=float32)>